
version: '3'

services:
  mariadb:
    image: "mariadb"
    container_name: "mariadb"
    build:
      context: requirements/mariadb
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    # env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    ports:
      - "3306:3306"

  nginx:
    image: "nginx"
    container_name: "nginx"
    build:
      context: requirements/nginx
    restart: always
    # env_file: .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - "wordpress"
    ports:
      - "443:443"

  wordpress:
    image: "wordpress"
    container_name: "wordpress"
    build: 
      context: requirements/wordpress
    restart: always
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    environment: 
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOSTNAME=${MYSQL_HOSTNAME}
      - WP_URL=${WP_URL}
      - WP_ADMIN=${WP_ADMIN}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_ADMIN_MAIL=${WP_ADMIN_MAIL}
      - WP_USER=${WP_USER}
      - WP_USER_PASSWORD=${WP_USER_PASSWORD}
      - WP_USER_MAIL=${WP_USER_MAIL}
    networks:
      - inception
    depends_on:
      - "mariadb"
    ports:
      - "9000:9000"

networks:
  inception:

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/user42/data/wordpress' #a changer
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/user42/data/mysql' #a changer
