FROM alpine:3.12.7

ARG MYSQL_DATABASE=wordpress
ARG MYSQL_USER=jgao
ARG MYSQL_PASSWORD=password
ARG MYSQL_ROOT_PASSWORD=root_password

RUN apk update && apk add mariadb mariadb-client

RUN mysql_install_db --user=mysql --datadir=/var/lib/mysql --auth-root-authentication-method=normal

RUN mkdir -p /run/mysqld && chown -R mysql /run/mysqld

RUN sed -i "s|.*skip-networking.*|skip-networking = false|g" /etc/my.cnf.d/mariadb-server.cnf && sed -i "s|.*bind-address\s*=.*|bind-address=0.0.0.0|g" /etc/my.cnf.d/mariadb-server.cnf

RUN mysqld -umysql & \
    sleep 10 && \ 
    echo "CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE};" | mysql && \
    echo "CREATE USER '${MYSQL_USER}'@'localhost' IDENTIFIED BY '${MYSQL_PASSWORD}';FLUSH PRIVILEGES;" | mysql && \
    echo "GRANT ALL PRIVILEGES ON wordpress.* TO '${MYSQL_USER}'@'localhost'; FLUSH PRIVILEGES;" | mysql && \
    echo "SET PASSWORD FOR '${MYSQL_USER}'@'localhost' = PASSWORD('${MYSQL_PASSWORD}');" | mysql && \
    echo "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('${MYSQL_ROOT_PASSWORD}');" | mysql


CMD ["mysqld", "--user=mysql"]

EXPOSE 3306
