version: "3"

  services:
    mariadb:
      container_name: "mariadb"
      build:
      context: docker/mariadb
      env-file: .env
      restart: unless-stopped
      volumes:
        - mariadb:/var/lib/mysql
      network:
        - inception

    wordpress:
      container_name: "wordpress"
      build: 
      context: docker/wordpress
      env-file: .env
      restart: unless-stopped
      volumes:
        - wordpress:/var/www/wordpress
      networks:
        - inception
      depends_on:
        - "mariadb"

    nginx:
      container_name: "nginx"
      build:
      context: docker/nginx
      restart: unless-stopped
      volumes:
        - wordpress:/var/www/wordpress
      networks:
        - inception
      depends_on:
        - "wordpress"

  networks:
    inception:
    driver: bridge

  volumes:
    wordpress:
      driver: local
      driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/jgao/data/wordpress'
    mariadb:
      driver: local
      drivers_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/jgao/data/wordpress'