FROM	debian:buster

RUN		apt-get update && apt-get upgrade -y && apt-get install php-fpm php-mysql wget mariadb-client -y

RUN		wget https://fr.wordpress.org/wordpress-6.1.1-fr_FR.tar.gz -P /var/www

RUN		cd /var/www && tar -xzf wordpress-6.1.1-fr_FR.tar.gz && rm wordpress-6.1.1-fr_FR.tar.gz

RUN		chown -R root:root /var/www/wordpress

RUN		wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar

RUN		chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp

RUN		sed -i 's/listen = \/run\/php\/php7\.3-fpm\.sock/listen = 0\.0\.0\.0:9000/g' /etc/php/7.3/fpm/pool.d/www.conf

COPY	/tools/config.sh .

RUN		chmod 755 config.sh

ENTRYPOINT [ "/config.sh" ]

EXPOSE	9000
