FROM	debian:buster

RUN		apt-get update && apt-get upgrade -y && apt-get install nginx -y \
		&& apt-get install openssl -y

COPY	/tools/nginx.conf /etc/nginx/conf.d

RUN		chmod 755 /var/www/html && \
		chown -R www-data:www-data /var/www/html

RUN		mkdir -p /etc/nginx/ssl && \
		openssl req -x509 -nodes -out /etc/nginx/ssl/inception.crt -keyout /etc/nginx/ssl/inception.key -subj "/C=FR/ST=IDF/L=Paris/O=42/OU=42/CN=jgao@student.42.fr"

CMD		["nginx", "-g", "daemon off;"]

EXPOSE	443